[package]
name = "rgpre"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs_io = "0.1.7"
encoding_rs = "0.8.30"

[build-dependencies]
cc = "1.0.73"
